2021-04-28T14:43:10.3124152Z ##[group]Run mypy src
2021-04-28T14:43:10.3124679Z [36;1mmypy src[0m
2021-04-28T14:43:10.3166984Z shell: /usr/bin/bash -e {0}
2021-04-28T14:43:10.3167418Z env:
2021-04-28T14:43:10.3168023Z   pythonLocation: /opt/hostedtoolcache/Python/3.8.9/x64
2021-04-28T14:43:10.3168940Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.9/x64/lib
2021-04-28T14:43:10.3169549Z ##[endgroup]
2021-04-28T14:43:14.5750358Z Success: no issues found in 2 source files
